kind: ConfigMap
apiVersion: v1
metadata:
  name: ddns
data:
  config.yaml: |-
    providers: []
    methods: []
    addresses: []
    domains: []
---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: ddns
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: ddns
              configMap:
                name: ddns
          containers:
            - name: ddns
              image: ghcr.io/ztelliot/ddns:latest
              volumeMounts:
                - name: ddns
                  mountPath: /config.yaml
                  subPath: config.yaml
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
